### ISSUE TITLE
Filtri selectid ei allu "selected" tagile

### ISSUE THREAD

**Issue by argoroots** [argoroots/kogumelugu#19]
Kui JS-iga miskit valida siis lehel ei kuva mis on valitud

**Comment by KaurKirikall** [comment]
Näitab ju selectededil selected, ei saa murest aru.

https://www.dropbox.com/s/l9t0nif64x2nwgm/Screenshot%202016-03-24%2012.05.21.png?dl=0

**Comment by argoroots** [comment]
https://www.dropbox.com/s/4lsf7tw2kt79ski/Screenshot%202016-03-24%2012.07.05.png?dl=0

**Comment by KaurKirikall** [comment]
Ei oska sellega ausalt öeldes midagi peale hakata... Kood iseenesest on see customselect.js :/

**Comment by mitselek** [comment]
lahendame #39 raames
