### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by mitselek** [argoroots/kogumelugu#22]
#18 depends on this

f4639fd has some missing translations:
- [x] Proovisid vaadata täispikka intervjuud, kuid selle jaoks pead olema sisselogitud.
- [x] Vali sobiv sotsiaalmeediateenus, mida soovid sisselogimiseks kasutada
- [x] Sisenedes portaali nõustud, et sinu andmeid kasutatakse portaali täiustamise huvides, kuid ei avalikustata kolmandatele osapooltele.

**Comment by eestimaluinstituut** [comment]
You tried to watch a full-length interview but you need to be logged in for that
Select the appropriate social media service for logging in 
By entering the portal you agree that your data will be used in the interests of improving the portal but will not be disclosed to third parties
