### ISSUE TITLE
Kategooriate põhine filtreering ei tööta

### ISSUE THREAD

**Issue by mitselek** [argoroots/kogumelugu#5]
- [ ] Probleem selles, et juba valitud kategooriat ei saa enam maha võtta;
- [ ] seotud teema on #4, filtrid peavad samuti sessioonis salvestuma

**Comment by argoroots** [comment]
Sama mis #17

**Comment by mitselek** [comment]
las see olla lahti, kuni saab filtreid maha võtta

**Comment by argoroots** [comment]
#29
