### ISSUE TITLE
Täispikkad intervjuud - võttame maha sisselogimine

### ISSUE THREAD

**Issue by michaelasnopkova** [argoroots/kogumelugu#50]
@mitselek, kas saaksime kohe maha võtta selle piirangu, et täispikkade intervjuude vaatamiseks peab sisse logima?

**Comment by mitselek** [comment]
sain maha võtta piirangu :)

mihkel
5656 0978

2017-03-13 12:36 GMT+02:00 michaelasnopkova <notifications@github.com>:
